openapi: 3.0.0
info:
  title: Auth API
  version: 1.0.0
  description: API documentation for the Auth service
servers:
  - url: https://6z8zmvfa3a.execute-api.us-east-1.amazonaws.com/prod/
paths:
  /token:
    get:
      summary: Auth user by token
      operationId: basicAuthorizer
      parameters:
        - in: header
          name: Authorization
          required: true
          schema:
            type: string
          description: The Basic Authorization token
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Authorized successfully               
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '500':
          description: Bad Request
      security:
        - basicAuth: []
components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
